# Site settings
title: Skarlet Corp. IT and Security Services
description: Skarlet Corp. Managed IT and Cyber Security Services in Dixie County Florida
baseurl: "" # The subpath of your site, e.g., /blog or leave empty ""
url: "https://skarlet.org/" # The base URL of your site

# Author details
author:
  name: "J. Milford"
  email: "info@skarlet.org"

# Build settings
markdown: kramdown # Set the Markdown engine (kramdown is default in Jekyll)
theme: jekyll-theme-minimal # Built-in themes for GitHub Pages, can be changed
permalink: pretty # Pretty permalinks for clean URLs

# Defaults for layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination for posts
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude files or directories from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/

# Include specific files for processing (if needed)
include:
  - _pages
  - _posts
  - _documentation
  
collections:
  reviews:
    output: true
  posts:
    output: true

# Additional configuration (optional)
future: false; # Whether to publish posts with future dates
markdown_ext: "markdown,mkdown,mkdn,mkd,md" # Recognized Markdown file extensions
