name: Fix Gemfile Lock for Linux

on:
  workflow_dispatch:

jobs:
  fix-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: false

      - name: Add Linux platform
        run: |
          bundle lock --add-platform x86_64-linux
          cat Gemfile.lock

      - name: Commit updated lockfile
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add Gemfile.lock
          git commit -m "Add x86_64-linux platform to Gemfile.lock"
          git push
